package ru.uzden.uzdenbot.services;

public enum AdminAction {
    ADD_SUBSCRIPTION,
    CHECK_SUBSCRIPTION,
    REVOKE_SUBSCRIPTION,
    DISABLE_USER,
    ENABLE_USER,
    BROADCAST,
    CREATE_RU_EU_KEY,
    CREATE_REFERRAL_LINK,
    REFERRAL_LINK_STATS,
    RESET_REFERRAL_LINK_COUNTER,
    DELETE_REFERRAL_LINK,
    CREATE_ADMIN_KEY,
    RENEW_ADMIN_KEY
}
